### ISSUE TITLE
color changes when file in different folders

### ISSUE THREAD

**Issue by wushixong** [robb0wen/synthwave-vscode#152]
Hi, I am a programer of C++ and love your color theme VERY MUCH. 
But I find that when the same file in different folder depth, the color style changes simultaneously.
Here are the screen shots in the blow.
![image](https://user-images.githubusercontent.com/9802759/75745483-6ae02f80-5d52-11ea-8f5f-9fbdb741913e.png)
![image](https://user-images.githubusercontent.com/9802759/75745493-6f0c4d00-5d52-11ea-896a-8eb1b4a69f2a.png)

as you can see, the .cc file is in dialog-manager/src/ctrl，the depth is 3, but when I change the file location, the color style changes magically:
![image](https://user-images.githubusercontent.com/9802759/75745501-75022e00-5d52-11ea-9aa6-2b0cef910299.png)
![image](https://user-images.githubusercontent.com/9802759/75745507-7af80f00-5d52-11ea-977b-cd2b29102a77.png)
as you can see, the .cc file is in src/ctrl，the depth is 2 . 
so could you tell me how can I change the style when the depth is 3 ?

**Comment by Alomerovic** [comment]
Hey @wushixong, were you able to fix it somehow? I'm asking because I'm facing the same issue right now. I also noticed that when I'm launching vscode with a C file already opened, the colors are correct but after a few seconds, it does changes drastically and I don't know what to do anymore :( 

**Initially loads like this**
![image](https://user-images.githubusercontent.com/19373755/82844960-e74d5f00-9eb8-11ea-934d-9f340b4ca172.png)


**After a few seconds, changes to this**
![image](https://user-images.githubusercontent.com/19373755/82844966-f46a4e00-9eb8-11ea-9e17-cdbd7017e4f9.png)

**Comment by Alomerovic** [comment]
Hi @wushixong 
I've just found out that this issue does not rely on SynthWave's theme, but to a colorization option from C/C++ vscode extension lol 
So, basically you have to go to vscode settings (File > Preferences > Settings), then look for the left menu options and navigate through Extensions > C/C+. 
At this point, just search for the option: **C_Cpp: Enhanced Colorization** and disable it (default is enabled).

**Comment by wushixong** [comment]
> Hi @wushixong
> I've just found out that this issue does not rely on SynthWave's theme, but to a colorization option from C/C++ vscode extension lol
> So, basically you have to go to vscode settings (File > Preferences > Settings), then look for the left menu options and navigate through Extensions > C/C+.
> At this point, just search for the option: **C_Cpp: Enhanced Colorization** and disable it (default is enabled).

Ahhh, it works. 😆😆👍👍
