### ISSUE TITLE
ERR: Something went wrong when starting neon dreams 

### ISSUE THREAD

**Issue by Jasmin2895** [robb0wen/synthwave-vscode#158]
Hey,

I am trying to enable the glow by selecting enable neon dreams but it keeps giving me this error message.
<img width="1133" alt="Screenshot 2020-03-30 at 10 32 36 PM" src="https://user-images.githubusercontent.com/8161593/77940712-b4cb1f80-72d6-11ea-9186-6c88ee6dc50f.png">

Any help would be really appreciated, thanks in advance! 🙂

**Comment by torreslais** [comment]
Same here! :cry: 
Any help?

**Comment by sudeg** [comment]
same! 
Please help :'(

**Comment by RavisaraDev** [comment]
Try this. It works for me [Link](https://github.com/robb0wen/synthwave-vscode/issues/143)

**Comment by Duyan400** [comment]
I had the same issue and did what @RavisaraDev link recommended and it did work but only when i ran VSCode as root , witch is out of the question. One of the comments highlighted that this behavior was mostly due to VSCode being installed with snap (im on Ubuntu). 

I uninstalled VSCode snap version : sudo snap remove code

then i followed the instruction in the previous link . worked like a charm!

**Comment by kissu** [comment]
A bummer that this one does not work with `snap`, it's so nice to use.
