### ISSUE TITLE
Impossible to enable glow effect without run Vscode as admin on Mac

### ISSUE THREAD

**Issue by actlikeadam** [robb0wen/synthwave-vscode#175]
Problem currently present on MacOs Catalina but probably it's a more general problem. 
Forcing vscode to run as admin doesn't solve the problem, doing this it's possible to enable the glow effect, but the vscode installation will appear to be corrupted and the glow effect will be removed after an update

**Comment by robb0wen** [comment]
Hi, due to limitations of VS code extensions, all of the points raised are expected behaviour and are covered in the extension readme.

Because the extension needs to modify the core vscode files, admin rights are required. Making this modification then causes a checksum mismatch which VS code interprets as the app being corrupted. This message can be dismissed safely, or removed with the fix checksums plugin. Lastly, updates to VS code will replace the modified files, so you will need to rerun the enable neon dreams function to see the glow again
