### ISSUE TITLE
Colors washed out on mac

### ISSUE THREAD

**Issue by joelnet** [robb0wen/synthwave-vscode#37]
I installed this on my Ubuntu computer and the colors look amazing.

I installed this on my Mac and the colors aren't as vibrant as Linux and do not look like the screenshot on the main page. It still looks great, but the colors 
are more white and the glow is also less.

Screenshot attached for comparison.

Mac
<img width="600" alt="theme" src="https://user-images.githubusercontent.com/742630/57049242-09c86680-6c2c-11e9-9d30-a2d839647395.png">

Original
<img width="600" alt="theme" src="https://user-images.githubusercontent.com/742630/57049283-30869d00-6c2c-11e9-846e-5b6622429037.png">

I am also using Fira Code 100 (weight) with ligatures.

**Comment by robb0wen** [comment]
It's possible that the version you have installed on Linux is an older version. 

From v0.0.3 onwards the glow has a slight opacity added to increase readability. Because of the manual installation process, the CSS file doesn't automatically update when the extension does. This means that the CSS on your Linux install will have remainedthe same as it was when it was first installed, regardless of the extension version number.

I'm going to update the readme screenshot in the next release. The current screenshot was the one I posted in my original tweet, however that was taken very early on and I don't feel that it is as representative of the final project as I would like (strings, for example, are white in the original screenshot).

**Comment by joelnet** [comment]
I installed it on my Mac today and Linux yesterday. When I go home I will confirm the css files to see if there are any differences.

Either way, it's amazing. And thanks!

**Comment by joelnet** [comment]
Okay so it seems there were different versions. Linux was on 0.0.2, Mac was on 0.0.4.

0.0.2 Definitely had more bloom.

I have updated both of them to 0.0.6 and I am seeing some very minor differences differences. (probably due to displays). It's hard to tell when these screenshots are resized small, but if you click on them, and look at the `HTML` or the `/>` brackets, you can see the Mac loses a little bit of the blue.

So seems like it was due to different versions. I definitely prefer the bloom in 0.0.2 for the Mac though.

Cheers!

Ubuntu
![synth-0 0 6](https://user-images.githubusercontent.com/742630/57056078-e960d200-6c54-11e9-9739-2a4a0803ca39.png)

Mac
<img width="798" alt="synth-mac-0 0 6" src="https://user-images.githubusercontent.com/742630/57056082-efef4980-6c54-11e9-892e-2a0066c3fd42.png">
