### ISSUE TITLE
 - question about the glow and theme - Hi!

### ISSUE THREAD

**Issue by gregcousin126** [robb0wen/synthwave-vscode#57]
Hello, I am really liking the glow aspect of the theme and was wondering if it's possible to use the same glow theme on my theme somehow. Would you be able to give me some pointers on how to incorporate it on another theme? I've tried to change the custom CSS file but am not sure on how to fo the appropriate values. Heres the theme I'm trying to change it on :) = xotopio.xotopio-dark

**Comment by robb0wen** [comment]
I used VS code's built in devtools to find out the appropriate classnames needed to customise the CSS. These are the `.mtkX { ... }` classes you see in the CSS file. It's best to adjust the main theme colours first though, because the classes get generated and the classname changes as you add and remove colours in the theme json file.

Hope that helps!
