### ISSUE TITLE
Increase Glow Amount 

### ISSUE THREAD

**Issue by varun2948** [robb0wen/synthwave-vscode#96]
How Can I Increase the Glow Amount Cuz I Want More of That  ?  I saw one issue which suggested to change *.mtk but which one and which px to change (increase) BTW I Absolutely Loved Your Work Kudos :)  :+1:

**Comment by altimmons** [comment]
change the ranges in the custom css-  the "glow" is technically a shadow- only set to be lighter rather than the usual darker--

below- the distances are px- increase them. What you see is a gradient- at 2px distance (offset by 0x and 0y) - fading to color 2 at 3px (also offset 0,0), then 8px.  To increase glow- either increase the distance by increasing the px value, or decreasing the alpha- the last 2 digits of the hex color.  (#RRGGBBAA) or (#RGBA) values are 0-F (0-15).  If you need more help, check the internet for html or css help.

```
.mtk6 {
    color: #fdfdfd;
    text-shadow: 0 0 2px #001716, 0 0 3px #03edf975, 0 0 5px #03edf975, 0 0 8px #03edf975;
  }
  
  .mtk7 {
    color: #fff5f6;
    text-shadow: 0 0 2px #000, 0 0 10px #fc1f2c75, 0 0 5px #fc1f2c75, 0 0 25px #fc1f2c75;
  }
```

So those lines can be edited here:

> text-shadow: 0 0 _**2px**_ #000, 0 0 _**10px**_ #fc1f2c**_75_**, 0 0 **_5px_** #fc1f2c**_75_**, 0 0 25px #fc1f2c**_75_**;

could become:

> text-shadow: 0 0 _**4px**_ #000, 0 0 _**13px**_ #fc1f2c**_A0_**, 0 0 **_5px_** #fc1f2c**_A0_**, 0 0 30px #fc1f2c**_99_**;

**Comment by varun2948** [comment]
Thank You for the css needed it :) its perfect
